# Nombre de la aplicación
spring.application.name=gym-backend

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/GYMdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.sql.init.mode=never
spring.sql.init.platform=postgresql
spring.jpa.defer-datasource-initialization=true

