# Nombre de la aplicación
spring.application.name=gym-backend

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/GYMdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

# Puerto del servidor
server.port=8080
